# -*- coding: utf-8 -*-
"""TTS_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TV3Qo9KEo-Ct8-vfSIcej96VyUvI2k0g
"""

import torch

#Tacotron2 Dataset load (만약 GPU가 없다면, 'cuda'부분을 지워야 함)
tacotron2 = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_tacotron2', model_math='fp16')
tacotron2 = tacotron2.to('cuda')
tacotron2.eval()

waveglow = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_waveglow', model_math='fp16')
waveglow = waveglow.remove_weightnorm(waveglow)
waveglow = waveglow.to('cuda')
waveglow.eval()

# 파이썬 환경에서 음성 재생
from IPython.display import Audio

text = """
choi jae beom byeong sin
"""

utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_tts_utils')
sequences, lengths = utils.prepare_input_sequence([text])

with torch.no_grad():
    mel, _, _ = tacotron2.infer(sequences, lengths)
    audio = waveglow.infer(mel)
audio_numpy = audio[0].data.cpu().numpy()
rate = 22050

Audio(audio_numpy, rate=rate)

# 오디오 저장
from scipy.io.wavfile import write


text = """
 in the only sense with which we are at present concerned
 differs from most if not from all the arts and crafts represented in the Exhibition|Printing
  in the only sense with which we are at present concerned
"""

utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_tts_utils')
sequences, lengths = utils.prepare_input_sequence([text])

with torch.no_grad():
    mel, _, _ = tacotron2.infer(sequences, lengths)
    audio = waveglow.infer(mel)
audio_numpy = audio[0].data.cpu().numpy()
rate = 22050

write("LJ001-0001.wav", rate, audio_numpy)